services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app -b 0.0.0.0:$PORT --timeout 600
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
