services:
  - type: worker
    name: tiktok-throw-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_simple.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
